behaviors:
  PoliceBrain:
    trainer_type: poca
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 1500000
    time_horizon: 64
    summary_freq: 50000
    threaded: false
    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 12500
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0

  ThiefBrain:
    trainer_type: poca
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 1500000
    time_horizon: 64
    summary_freq: 50000
    threaded: false
    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 200000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
